### ISSUE TITLE
Deploy this demo on metropole

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Demo-VCity-UI-driven-data-computation-Lyon#1]
- [x] Dockerize the demo in the ad-hoc repository 
- [x] [Deploy on the Metropole server](https://github.com/VCityTeam/VCity-Deployments/tree/master/Metropole)

**Comment by LorenzoMarnat** [comment]
[Docker](https://github.com/VCityTeam/UD-Demo-VCity-UI-driven-data-computation-Lyon-docker)
[Online demo](https://ui-driven-lyon.vcityliris.data.alpha.grandlyon.com/)

**Comment by EricBoix** [comment]
Well done ! Congrats.
